---
resources:
- name: java-buildpack
  type: git
  icon: github
  source:
    uri: https://github.com/cloudfoundry/java-buildpack.git
    branch: ci-test

- name: cf-deployment
  type: git
  icon: github
  source:
    uri: https://github.com/cloudfoundry/cf-deployment.git
    branch: main

- name: cf-deployment-concourse-tasks
  type: git
  icon: github
  source:
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git
    branch: main

- name: buildpack-version
  type: semver
  icon: tag
  source:
    driver: s3
    bucket: buildpacks.cloudfoundry.org
    key: versions/java-buildpack/version
    access_key_id: ((buildpacks-cloudfoundry-org-aws-access-key-id))
    secret_access_key: ((buildpacks-cloudfoundry-org-aws-secret-access-key))
    region_name: us-east-1
    initial_version: 4.80.0

- name: buildpack-github-release
  type: github-release
  icon: github
  source:
    owner: cloudfoundry
    repository: java-buildpack
    access_token: ((github_access_token))

jobs:
- name: unit-tests
  public: true
  plan:
  - get: java-buildpack
    trigger: true
  - task: run-unit-tests
    file: java-buildpack/ci/tasks/unit-tests/task.yml

- name: build-buildpack
  public: true
  plan:
  - in_parallel:
    - get: java-buildpack
      passed: [unit-tests]
      trigger: true
    - get: buildpack-version
      params: {bump: patch}
  - task: build-online-buildpack
    file: java-buildpack/ci/tasks/build-buildpack/task.yml
  - put: buildpack-version
    params: {file: buildpack-version/version}

- name: integration-tests-docker
  public: true
  plan:
  - get: java-buildpack
    passed: [build-buildpack]
    trigger: true
  - task: build-buildpack-for-tests
    file: java-buildpack/ci/tasks/build-buildpack/task.yml
  - task: run-integration-tests-docker
    file: java-buildpack/ci/tasks/integration-tests-docker/task.yml
    privileged: true
    params:
      GITHUB_TOKEN: ((github_token))

- name: integration-tests-cf
  public: true
  serial: true
  plan:
  - in_parallel:
    - get: java-buildpack
      passed: [integration-tests-docker]
      trigger: true
    - get: cf-deployment
    - get: cf-deployment-concourse-tasks
  
  - task: build-buildpack-for-tests
    file: java-buildpack/ci/tasks/build-buildpack/task.yml
  
  # Step 1: Create CF environment with BBL
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    output_mapping:
      updated-bbl-state: bbl-state
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: ((gcp_service_account_key))
      BBL_GCP_REGION: europe-north1
      BBL_ENV_NAME: java-buildpack-ci
      BBL_LB_CERT: ((shared-cf-cert.certificate))
      BBL_LB_KEY: ((shared-cf-cert.private_key))
      LB_DOMAIN: java-buildpack.buildpacks.ci.cloudfoundry.org
      BBL_STATE_DIR: .
  
  # Step 2: Deploy Cloud Foundry
  - task: bosh-deploy-cf
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    input_mapping:
      bbl-state: bbl-state
      cf-deployment: cf-deployment
      ops-files: cf-deployment
      vars-files: bbl-state
    output_mapping:
      updated-bbl-state: bbl-state
    params:
      SYSTEM_DOMAIN: java-buildpack.buildpacks.ci.cloudfoundry.org
      BBL_STATE_DIR: .
      OPS_FILES: |
        operations/use-compiled-releases.yml
        operations/experimental/fast-deploy-with-downtime-and-danger.yml
        operations/scale-to-one-az.yml

  # Step 3: Run Switchblade integration tests on CF
  - task: run-integration-tests-cf
    file: java-buildpack/ci/tasks/integration-tests-cf/task.yml
    params:
      SYSTEM_DOMAIN: java-buildpack.buildpacks.ci.cloudfoundry.org
      GITHUB_TOKEN: ((github_token))
    ensure:
      do:
      # Step 4: Cleanup BOSH environment
      - task: bosh-cleanup
        file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
        input_mapping:
          bbl-state: bbl-state
        output_mapping:
          updated-bbl-state: bbl-state
        params:
          BBL_STATE_DIR: .
      
      # Step 5: Destroy infrastructure
      - task: bbl-destroy
        file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
        input_mapping:
          bbl-state: bbl-state
        params:
          BBL_STATE_DIR: .
          BBL_GCP_SERVICE_ACCOUNT_KEY: ((gcp_service_account_key))

- name: ship-it
  public: true
  serial: true
  plan:
  - in_parallel:
    - get: java-buildpack
      passed: [integration-tests-cf]
    - get: buildpack-version
  
  - task: create-release
    file: java-buildpack/ci/tasks/create-release/task.yml
  
  - put: buildpack-github-release
    params:
      name: release/name
      tag: release/tag
      body: release/body
      globs:
      - release/java-buildpack-*.zip
  
  - put: buildpack-version
    params: {bump: minor}
